In [1]:
import tensorflow as tf

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
a_1_list = [[1.0, 0.0, 1.0, 0.0, 1.0, 0.0]]
a_2_list = [[0.0, 1.0, 0.0, 1.0, 0.0, 1.0]]

b_list   = [[1.1, 3.1, 10.1, 2.1, 8.1, 2.1]]

In [3]:
# a, b will execute on CPU
with tf.device('/cpu:0'):
    a_1 = tf.constant(a_1_list, name='a1')
    a_2 = tf.constant(a_2_list, name='a2')
    a = a_1 + a_2
    b = tf.constant(b_list, name='b')

# c will execute on the GPU
with tf.device('/gpu:0'):
    b = tf.transpose(b)
    c = tf.matmul(a, b)



In [4]:
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

In [5]:
with tf.Session() as sess:
    print(sess.run(c))
# When working with multiple devices you should pass this to the tf.Session (handling uncompatibility issues):
#      config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)

[[26.6]]


In [6]:
with tf.Session() as sess:
    print(sess.run(a_1 + tf.constant(2.0)))

[[3. 2. 3. 2. 3. 2.]]


In [7]:
# Show all the nodes (ops)
[n.name for n in tf.get_default_graph().as_graph_def().node]

['a1',
 'a2',
 'add',
 'b',
 'transpose/Rank',
 'transpose/sub/y',
 'transpose/sub',
 'transpose/Range/start',
 'transpose/Range/delta',
 'transpose/Range',
 'transpose/sub_1',
 'transpose',
 'MatMul',
 'Const',
 'add_1']

In [8]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
p_out = p1 + p2
# Unlike constants, placeholders need to be fed during runtime
with tf.Session() as sess:
    print(sess.run(p_out, feed_dict={p1: [2, 2,2,2], p2: [2, 2,2,2]}))

[4. 4. 4. 4.]


In [9]:
v1 = tf.Variable(tf.random_normal([3,3],stddev=0.1))
v2 = tf.Variable(tf.random_normal([3,3],stddev=0.1))
v_out = v1 - v2

In [10]:
# Can't use Variables without initialization
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(v_out))

[[-0.04254613 -0.27068177  0.05738962]
 [ 0.22332385  0.021009    0.18146482]
 [-0.13367468 -0.0611604   0.0420726 ]]
